plugins {
    id 'com.android.application'
}

android {
    namespace 'kr.gnmc.knight'
    compileSdk 34

    defaultConfig {
        applicationId "kr.gnmc.knight"
        minSdk 24
        targetSdk 34
        versionCode Integer.parseInt(System.getenv('APK_VERSION_CODE') ?: '1')
        versionName System.getenv('APK_VERSION_NAME') ?: '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
